# Generated by Django 5.2.6 on 2025-09-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_skill_unique_skill_per_race'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_skill_per_race',
        ),
    ]
